### ISSUE TITLE
Item take inconsistency

### ISSUE THREAD

**Issue by recar** [CodinGameCommunity/XmasRush#95]
It seems by code item is taken by the end turn position. But in rules mentioned we can pass the item during turn to take it.

```
        if (hasActions()) {
            doPlayerActions();
            updateView();
            checkForFinishedItems();
        }
```

```
    private void doPlayerActions(){
        if (turnType.equals(Action.Type.PUSH)) {
            Map actions = pushActions.get(0);
            pushActions.remove(0);
            doPushAction(actions);
        } else {
            for (Map.Entry action : moveActions.entrySet()) {
                doMoveAction(action);
            }
            moveActions.values().removeIf(MoveAction::isEmpty);
            passActions = false;
        }
    }
```
Could be fixed by adding checkForFinishedItems(); after doMoveAction in a loop and adding one after doPushAction.

**Comment by Tzupy** [comment]
@recar please provide a seed and frame turn in which this issue happens.

**Comment by eulerscheZahl** [comment]
Seems to work fine ([frame 46](https://www.codingame.com/replay/356977452)).

**Comment by chickentuna** [comment]
> Seems to work fine ([frame 46](https://www.codingame.com/replay/356977452)).

While I'm here, did you know you can set the frame at which a replay start by adding ?f=46
(https://www.codingame.com/replay/356977452?f=46)

**Comment by eulerscheZahl** [comment]
Yes, Thibaud even shared it as hint 9 on the [blog](https://www.codingame.com/blog/tips-make-most-codingame-platform/).
I just forget the syntax all the time and don't want to test. :frowning_face:

**Comment by Tzupy** [comment]
Closing as not an issue.

**Comment by recar** [comment]
Yes, it seems to work in game. Is the game referee the same as provided here?
I still can't see how it can work with github referee version =).

**Comment by recar** [comment]
Thanks for explaining
